### ISSUE TITLE
ValueError: ''X'' is not a valid unambiguous letter for protein

### ISSUE THREAD

**Issue by yemilawal** [DamianJM/Depolymerase-Predictor#3]
I tried to run depp_cli on a few protein sequences with the following command:
`./depp_cli.py -i input.fasta -o output_directory` and I got the following error:

`Traceback (most recent call last):
  File "/XXXX/XXXX/Depolymerase-Predictor/DePP_CLI/./depp_cli.py", line 46, in <module>
    main()
  File "/XXXX/XXXX/Depolymerase-Predictor/DePP_CLI/./depp_cli.py", line 27, in main
    protein_parameters = [calculate_protein_parameters(protein_record) for protein_record in protein_records]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXX/XXXX/Depolymerase-Predictor/DePP_CLI/utils/data_processing.py", line 57, in calculate_protein_parameters
    protein_params = prot_params(seq)
                     ^^^^^^^^^^^^^^^^
  File "/home/yemi/Depolymerase-Predictor/DePP_CLI/utils/data_processing.py", line 18, in prot_params
    x.molecular_weight(),
    ^^^^^^^^^^^^^^^^^^^^
  File "/XXXXXX/XXXXXX/XXXXXXX/envs/depp_cli/lib/python3.12/site-packages/Bio/SeqUtils/ProtParam.py", line 124, in molecular_weight
    return molecular_weight(
           ^^^^^^^^^^^^^^^^^
  File "/XXXXXX/XXXXXX/XXXXXXX/envs/depp_cli/lib/python3.12/site-packages/Bio/SeqUtils/__init__.py", line 474, in molecular_weight
    raise ValueError(
ValueError: ''X'' is not a valid unambiguous letter for protein`

One of the sequences in the input file had 'X'. I removed this sequence and re-run and it seems to work fine. I do have a couple of other sequences with 'X' and as I understand, 'X' is used to depict that the identity of an amino acid is undetermined, or the amino acid is atypical. Is there any fix for this?

Thank you for your help

**Comment by TimSkvortsov** [comment]
Hi @yemilawal, thanks for using our program! This is not something we will be able to fix easily - it is intended behaviour of the BioPython's Bio.SeqUtils.ProtParam module, please see here:
https://github.com/biopython/biopython/issues/1863
As X is not an unambiguous amino acid, the parameters for a protein containing one or more X cannot be calculated. A workaround would be to replace all X in your amino acid sequences with a specific amino acid like alanine or remove all sequences containing X. We considered implementing an autoreplacement, but decided against that in the end to make sure that the users are aware of the problems with their sequences and to allow them to decide what to do in such situations themselves.

**Comment by yemilawal** [comment]
@TimSkvortsov - Thanks for the prompt response. I removed all sequences containing 'X', but encountered another error, this time with sequences containing "B" ("ValueError: ''B'' is not a valid unambiguous letter for protein). I'm guessing this will require the same 'fix' as with "X".
Thanks for your help.

**Comment by TimSkvortsov** [comment]
Yes, I am afraid that there is no better way around that unless you can obtain full sequence of your protein of interest somehow. You can substitute ‘B’ with aspartic acid and asparagine (D or N), but it is not a very reliable approach.
